# Generated by Django 4.0.6 on 2022-07-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Auto',
        ),
    ]
