# Generated by Django 4.0.6 on 2022-07-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_moto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moto',
        ),
    ]
