# Generated by Django 4.0.6 on 2022-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_delete_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
