# Generated by Django 4.0.6 on 2022-08-02 00:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=40)),
                ('contenido', ckeditor.fields.RichTextField(null=True)),
                ('autor', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
    ]
