# Generated by Django 4.0.6 on 2022-08-02 00:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='masdatosusuario',
            name='red_social',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
